import type { SiteLang } from './lang';

/** Paired page copy; order and technical values follow the existing Lab page. */
export const LAB_PAGE_COPY: readonly (readonly [string, string])[] = [
  ["Behaviour", "行为"],
  ["Visitors walk the floor and cats live on the units; the units follow both and the four encounter events are counted.", "访客在地面走，猫住在单元上；单元按两边的痕迹落下收回，四类相遇事件实时记数。"],
  ["Visitors walk the floor; resident cats live on the units. Formed units are walls for people and footing for cats. The space pins a cat’s unit, fills the neighbour with the strongest people trace, and holds back any unit that would trap someone. Four encounter events are counted as they happen.", "访客在地面走，住户猫住在单元上。落下的单元对人是墙、对猫是落脚处。空间钉住猫脚下的单元，补满猫四邻里人的痕迹最高的一格，落下会困住人的不落。四类相遇事件随发生随记。"],
  ["Room", "房间"],
  ["Lab 2-8 room · 4×4 real units · 6×6 / 8×8 scaled", "Lab 2-8 那间 · 4×4 真实单元 · 6×6 / 8×8 等比缩小"],
  ["Passage cost", "通行代价"],
  ["Formed unit = wall for people (≥ 50% formed) · not for cats · people route along the aisles", "落下的单元（成形 ≥ 50%）对人是墙 · 对猫不是 · 人沿过道绕行"],
  ["Staying cost", "停留代价"],
  ["Person: another within 1.35 m for 2 s → leave · Cat: visitor within 1 m tolerated 6 s (14 s when watched) → retreat, 15 s latency", "人：别人进到 1.35 m 以内满 2 s 就走 · 猫：访客进到 1 m 以内能忍 6 s（被盯着看时 14 s），然后退开、15 s 潜伏"],
  ["Rules", "五条规则"],
  ["R1 space writes units only · R2 bodies read costs only · R3 bodies choose · R4 judged by events · R5 nobody trapped", "R1 空间只写单元 · R2 个体只读代价 · R3 去向自己选 · R4 只按事件评 · R5 谁都不被困住"],
  ["Events", "事件"],
  ["Co-gaze ≥ 1 s · co-warmth 0.5–1.5 m ≥ 2 s · contact < 0.5 m · crossing through the 1.5 m domain", "共视 ≥ 1 s · 共温 0.5–1.5 m 带内 ≥ 2 s · 共触 < 0.5 m · 交接 = 穿过 1.5 m 身体域"],
  ["Comparison", "对照"],
  ["Live units · fixed (even rows formed) · empty room", "会动的单元 · 钉死（偶数行落下）· 空房间"],
  ["Sources", "出处"],
  ["1.35 m stranger distance (42-country survey) · 1 m cat band and 78% reference (Mertens & Turner 1988)", "陌生人距离 1.35 m（42 国调查）· 猫的 1 m 档与 78% 参照（Mertens 与 Turner 1988）"],
  ["Timings and the 1/3 approach chance are demonstration values; no invitation gesture, so the empty event is not counted", "各秒数与三分之一的靠近几率是演示值；没有招引动作，空事件不记"],
  ["Watch a cat move across the units; occupied platforms stay open and the next landing activates ahead.", "观察猫在单元上移动：脚下平台维持展开，下一落点提前激活。"],
  ["The cat lives on the units. Its current platform stays open; the next landing forms before it moves. Choose a behaviour, click a destination or drag the cat onto a unit.", "猫在单元上生活。脚下平台保持展开，下一落点成形后再移动。选择行为、点击目标，或把猫拖到单元上。"],
  ["Pass through · seated / lying rest · toy play · free sequence", "通行 · 坐卧休息 · 玩具游戏 · 自由轮换"],
  ["Visits leave traces on platform surfaces", "使用痕迹留在经过的平台表面"],
  ["Occupied units stay open; the next landing activates before departure", "脚下单元保持展开；下一落点在出发前激活"],
  ["Plan view only; transfer reach, jump height and loads are not simulated", "仅俯视演示；尚未模拟转移可达性、跳跃高度与承重"],
  ["Round to square, with independent shelf sizes, tilts, gaps and joins.", "圆环变方环，同时保留各层尺寸、倾斜、缺口与局部连接。"],
  ["Morph the ring from round to square and adjust shelf sizes, tilts and gaps. Join depth ranges from 0% to 100%: 100% meets both rims; 50% fills the inner half. Forming bands and skin follow the assembly; Sections shows the original solve.", "从圆环逐档变成方环，调整上下层尺寸、倾斜与缺口。连接深度可调 0–100%：100% 与外缘齐平，50% 只占内半段。条带与蒙皮随装配变化；截面对照保留原始求解结果。"],
  ["70–130 per layer · maximum axis-to-rim distance", "每层 70–130 · 中轴到最远外缘"],
  ["Ring shape", "环形轮廓"],
  ["Five steps from circle to square · fixed maximum radius", "圆到方五档 · 最大外伸半径不变"],
  ["Four profiles · 20 base slots, split at gaps and square corners", "四类截面 · 20 个基础槽，缺口与方角处分槽"],
  ["No circumferential forces; shape, size, join depth and tilt are assembly previews", "未模拟环向受力；圆方、尺寸、连接深度与倾斜为装配预览"],
  ["One sector or two opposite sectors · depth 0–100%", "单区或对向双区 · 连接深度 0–100%"],
  ["Drag a free joint to drive the four-bar linkage. Release it to see the crank resume and the coupler trace its path.", "拖动自由节点可以带动四杆连杆。松手后曲柄恢复运转，连杆上的标记点继续留下轨迹。"],
  ["2D PBD · Gauss–Seidel", "二维位置动力学 · 高斯–赛德尔"],
  ["36 tests", "36 项测试"],
  ["SVG · live coupler trace", "矢量绘制 · 实时轨迹"],
  ["Any free node · release damping", "拖动自由节点 · 松手阻尼"],
  ["Drag the apex, feet or crank pin to move the S4 scissor arch. Slot stops limit its travel.", "拖动拱顶、底脚或曲柄销，观察 S4 剪式拱环的开合。槽端止程限制它的活动范围。"],
  ["Shared 2D core", "共用二维内核"],
  ["S4 M3×1.000 · 14 plates", "S4 M3×1.000 · 14 块板"],
  ["Dual-end slot clamp · fixed step", "双向槽端止程 · 固定步长"],
  ["Apex / feet / crank pin", "拱顶／底脚／曲柄销"],
  ["Adjust three tendons to bend seven box vertebrae. Drag to rotate the scanned model.", "调节三条肌腱，使七节方盒椎节弯曲。拖动可旋转查看扫描模型。"],
  ["LinkageSolver3D · symmetric GS", "三维连杆求解器 · 对称高斯–赛德尔"],
  ["107k tri · real scan", "10.7 万三角面 · 实物扫描"],
  ["Drag to orbit · zoom controls · wheel zoom when expanded", "拖动旋转 · 按钮缩放 · 放大后可用滚轮缩放"],
  ["Tendon sliders · critical damping", "肌腱滑块 · 临界阻尼"],
  ["Five rings open and close together at 85 mm spacing. Adjust the phase and skin to inspect the structure.", "五个环以 85 毫米间距同步开合。调节相位和蒙皮，可以查看内部结构。"],
  ["S1–S5 · ladder 0 / 2 / 4 / 8", "S1–S5 · 止程余量 0／2／4／8"],
  ["In-phase · ω 0.8 · step 1/120 s", "同相 · 角速度 0.8 · 步长 1/120 秒"],
  ["0.24–0.42 mm", "0.24–0.42 毫米"],
  ["Run · phase · skin · views", "运转 · 相位 · 蒙皮 · 视角"],
  ["A shaft swings through 180° to open and close five rings. Three tendons bend the large arm.", "一根轴往复转动 180°，驱动五个环开合。三条肌腱控制大触手弯曲。"],
  ["Real solids · adjustable skin", "实物实体 · 蒙皮可调"],
  ["One shaft · five cranks · in phase", "一根轴 · 五个曲柄 · 同相"],
  ["180° reciprocating · apex ≡ 2R", "往复 180° · 拱顶行程等于 2R"],
  ["Three tendons · same solver as Lab 1-3", "三条肌腱 · 沿用实验 1-3 求解器"],
  ["Speed not to scale · small-arm motion choreographed", "速度不按实物比例 · 小触手动作是展示编排"],
  ["A hanging strip contracts into a pocket, bulb, ledge or stairs. Each shape uses a different pattern of locking bonds.", "悬挂的条带收缩成袋、蘑菇挑台、直挑台或阶梯挑台。每种形态由不同的锁定键排布决定。"],
  ["Position-based · Verlet + projection", "位置约束 · 韦尔莱积分＋投影"],
  ["Research-code port · parity ≤ 1e-9", "研究代码移植 · 数值误差 ≤ 1e-9"],
  ["Zipper locks · forming only", "拉链键锁定 · 只演示成形"],
  ["One contraction ℓ · four bond maps", "同一收缩量 ℓ · 四种键谱"],
  ["SVG · smoothing affects drawing only", "矢量绘制 · 平滑仅影响画面"],
  ["Rotate the four shapes from Lab 2-1 as solid fabric bands. Section edges show the material thickness and locking bonds.", "旋转查看实验 2-1 的四种织物带。剖面边缘显示材料厚度和锁定键。"],
  ["Lab 2-1’s 2D engine", "实验 2-1 的二维引擎"],
  ["Extruded section · thickness 5", "剖面挤出 · 厚度 5"],
  ["Drag to orbit · preset views", "拖动旋转 · 预设视角"],
  ["Visible on both section edges", "两侧剖口均可见"],
  ["WebGL", "WebGL"],
  ["One strip forms two structures under the same contraction. Choose a pair and adjust the fixed segment between them to compare how independently they fold.", "一条带在同一次收缩中形成两个结构。选择形态组合，调节中间固定段长度，比较两段成形是否相互影响。"],
  ["Fixed · free A · fixed · free B · fixed", "固定 · 自由段 A · 固定 · 自由段 B · 固定"],
  ["Four matching pairs · bulb above ledge", "四种同形对 · 蘑菇挑台在直挑台上方"],
  ["16 / 29 / 48 nodes", "16／29／48 个节点"],
  ["Gap ≥ 29: identical to separate runs; ≥ 16: difference < 1 px", "间距 ≥ 29：与独立运行一致；≥ 16：误差 < 1 像素"],
  ["One contraction ℓ for both structures", "两个结构共用收缩量 ℓ"],
  ["Compare a 12-band transition from bulb to stepped box with a 10-stage split from one box into two platforms. Pack the bands together or spread them into a row.", "对比两组序列：十二条带从蘑菇挑台渐变为阶梯方箱，十个阶段从单箱分成上下平台。可并拢查看整体，也可分列逐条比较。"],
  ["Graded: 12 bands · split: 10 stages", "渐变：12 条带 · 捏分：10 个阶段"],
  ["Bond length 0.10 → 0.32", "键长 0.10 → 0.32"],
  ["Platforms 12 px thick · depth 40 px · final gap 28 px", "平台厚 12 像素 · 深 40 像素 · 最终缝宽 28 像素"],
  ["Outer ladder · seam zipper · face-corner bonds", "外梯挡 · 缝内拉链 · 面角锁定键"],
  ["Silhouette difference 0.3–3.7 px", "轮廓偏差 0.3–3.7 像素"],
  ["Packed body or spread row", "并拢成体或分列成排"],
  ["Twenty contracting bands form a platform around a tube. Choose a level, undulating, changing, split or double platform, then adjust the radius.", "二十条收缩带围绕中轴形成平台。选择等高、起伏、渐变、捏分或双层平台，再调节环的半径。"],
  ["20 bands · five arrangements", "20 条带 · 五种编制"],
  ["One shape placed at heights from 18% to 71% of the strip", "同一形态在条带 18%–71% 的高度范围内排列"],
  ["Two shelves, each 16 px thick · gap varies from 0 to 100 px", "两片台各厚 16 像素 · 间隙由 0 到 100 像素"],
  ["Two level shelves · constant 100 px gap", "两片等高环台 · 间隙恒为 100 像素"],
  ["Adjustable · gaps between bands widen with it", "半径可调 · 带间缝随之增大"],
  ["Opacity 0–1 · default 0.35; split/double 0.15", "不透明度 0–1 · 默认 0.35；捏分／双层为 0.15"],
  ["Independent 2D sections; no forces between bands", "独立二维剖面；未模拟带间作用力"],
  ["Adjust two shelves around one axis: tilt them, cut away sectors or join their edges. Switch to forming bands to inspect the sections and locking bonds. Tilt is an assembly preview; its forming mechanism is not simulated.", "调节同轴的两层台：改变倾角、切去扇区，或连接上下外缘。切到条带成形可查看剖面和锁定键。倾斜仅作装配预览，尚未模拟其成形机制。"],
  ["Target geometry · forming bands", "目标几何 · 条带成形"],
  ["Adjust each shelf’s radius, tilt and outline, or join their edges. In forming bands, use Skin to see the surface or expose the bands. Radius and tilt preview the assembly; Sections shows the original solved dimensions.", "分别调节上下层的半径、倾角和轮廓，也可连接两层外缘。成形演示中可调蒙皮透明度，查看表面或内部条带。半径与倾斜为装配预览，截面对照保留原始求解尺寸。"],
  ["70–130 per layer · axis to rim · assembly preview", "每层 70–130 · 中轴至外缘 · 装配预览"],
  ["Opacity 0–100% · default 35% · cutouts stay open", "不透明度 0–100% · 默认 35% · 保留缺口"],
  ["No circumferential forces; radius and tilt do not re-solve the sections", "未模拟环向受力；半径与倾斜不重算截面"],
  ["Lab 2-5 double platform · thickness 16 · gap 100 · reach 83.2", "实验 2-5 双层台 · 厚 16 · 间隙 100 · 挑出 83.2"],
  ["0–20° per layer · assembly preview", "每层 0–20° · 装配预览"],
  ["360° / 180° / 90° / 240° / two 90° sectors", "整环／半环／90°／240°／两个 90° 扇区"],
  ["One sector or two opposite sectors", "单个扇区或两个对向扇区"],
  ["Four profiles · 20 base slots, split at outline edges", "四种剖面 · 20 个基准槽在轮廓边界细分"],
  ["No circumferential forces or simulated tilt mechanism", "未模拟环向力和倾斜成形机制"],
  ["Twenty bands with different reaches form a square around a round mast. Change the outline from circle to square, or choose an undulating or split platform.", "二十条带以不同的挑出距离围绕圆轴形成方环。可将轮廓从圆调到方，也可选择起伏或捏分平台。"],
  ["20 total: 8 face · 8 edge · 4 corner", "共 20 条：面部 8 · 边部 8 · 角部 4"],
  ["Five steps from circle to square", "五档，从圆到方"],
  ["Side 169 px · platform height 36 px · rim error < 0.9 px", "边长 169 像素 · 台高 36 像素 · 外缘误差 < 0.9 像素"],
  ["Round 54 px · square 56 / 64 / 89 px", "圆形 54 像素 · 方形 56／64／89 像素"],
  ["40 px height range", "高度范围 40 像素"],
  ["Shelves 16 px thick · gap 0–100 px · seam centre stays level", "台厚 16 像素 · 间隙 0–100 像素 · 缝心等高"],
  ["Side 223 px · 338 nodes per band", "边长 223 像素 · 每条带 338 节点"],
  ["Single ring or 4×4 · fixed radius", "单环或 4×4 · 半径固定"],
  ["Split faces held straight by a placement rule during forming", "捏分成形时，由摆放规则保持端面平直"],
  ["Sixteen rings fill a room beside a 1.70 m figure. Change the form for the whole field or by row; adjust the radius to change the spacing.", "十六个环布置在房间内，以 1.70 米人物标示比例。可统一切换形态，也可每行一种；调节半径时，间距随之变化。"],
  ["4×4 rings · 20 bands each", "4×4 个环 · 每环 20 条带"],
  ["Figure 1.70 m · room 3.74 m · ring width 1.04 m", "人物 1.70 米 · 房高 3.74 米 · 环宽 1.04 米"],
  ["Platform underside 1.08 m", "平台底面离地 1.08 米"],
  ["Tracks radius · ring gap = 1.5× gap between bands", "随半径变化 · 环间缝为带间缝的 1.5 倍"],
  ["Same throughout or one per row", "全场同形或每行一种"],
  ["Adjustable membrane opacity, 0–1", "织物膜不透明度 0–1"],
  ["Arrange two, three, four or nine rings. Compare gaps, touching edges, steps and interleaving, then make them form together or in sequence. Combinations that would collide are disabled.", "组合二、三、四或九个环，比较分离、相切、错层和交叠关系，再选择同步或依次成形。会发生碰撞的组合不可选。"],
  ["Lab 2-5 ring · 20 bands · 202 nodes", "实验 2-5 的环 · 20 条带 · 202 节点"],
  ["2 / 3 / 4 / 9 rings", "2／3／4／9 个环"],
  ["Apart · touching · apart stepped · touching stepped · interleaved", "分离 · 相切 · 分离错层 · 相切错层 · 交叠"],
  ["Up to 0.35 m; shape stays unchanged", "最高 0.35 米，形态不变"],
  ["Step must clear the forming body by 6 px", "高差需超出成形中的结构厚度 6 像素"],
  ["Together or staggered by 150 steps", "同步或每隔 150 步启动一波"],
  ["Level touching edges joined by a 16 cm fabric web", "等高相切边用 16 厘米织物网连接"],
  ["Lab 2-8 room · 1.70 m figure", "实验 2-8 房间 · 1.70 米人物"],
  ["Move one person through the room and watch nearby units form. The floor records time spent within view. Follow mode withdraws the structure as that trace fades; lock mode keeps it formed.", "移动一个人，观察附近单元成形。地面记录视野范围内的停留时间。跟随模式随痕迹消退而收回结构；锁定模式保留成形。"],
  ["4×4 / 6×6 / 8×8 · Lab 2-8 room", "4×4／6×6／8×8 · 实验 2-8 房间"],
  ["0.1 m floor cells · capped at the threshold · linear fade", "0.1 米地面格 · 读数上限为阈值 · 线性消退"],
  ["Mean trace by cell or footprint", "按单元分区或平台投影读取均值"],
  ["Mean ≥ threshold × floor share; default share 50%", "均值 ≥ 阈值 × 占比；默认占比 50%"],
  ["Threshold 2 s · fade 6 s · follow mode", "阈值 2 秒 · 消退 6 秒 · 跟随模式"],
  ["Reach 0.22–2.0 m, default 1.5 m · angle 60°–360°, default 180°", "半径 0.22–2.0 米，默认 1.5 米 · 视角 60°–360°，默认 180°"],
  ["Platform radius + body 0.22 m + margin 0.15 m; walking lane twice this width", "平台半径＋身体 0.22 米＋余量 0.15 米；通道宽为其两倍"],
  ["15 s threshold · 2%/s decay, uncapped; differs from this demo", "阈值 15 秒 · 每秒衰减 2%，不封顶；与本演示不同"],
  ["Activation only; no behaviour-to-shape rule", "只研究激活，尚无行为到形态的规则"],
  ["Place up to eight people, drag them or let them wander. Their floor traces add where their views overlap, so units can form sooner. Activation and clearance use the same rules as Lab 2-10.", "最多放置八个人，可以拖动，也可以让他们自走。视野重叠处的地面痕迹会叠加，使单元更早成形。激活与让位规则沿用实验 2-10。"],
  ["Click to add · hold to drag · − removes the last", "点击添加 · 按住拖动 · 减号移除最后一人"],
  ["0.7 m/s · walks 0.5–2 m, occasionally 3.5 m · pauses 8–45 s", "步速 0.7 米/秒 · 每次走 0.5–2 米，偶尔 3.5 米 · 停留 8–45 秒"],
  ["Follow: withdraw as traces fade · lock: keep formed", "跟随：随痕迹消退收回 · 锁定：保留成形"],
  ["Two simultaneous views add trace at twice the rate", "两个视野同时覆盖时，痕迹累积速度翻倍"],
  ["4×4 / 6×6 / 8×8 · Lab 2-8 room", "4×4／6×6／8×8 · 实验 2-8 房间"],
  ["Random wandering for demonstration; not a model of human behaviour", "随机漫步仅用于演示，不是人的行为模型"],
  ["Join round or square platforms into steps, ramps and enclosures. Adjust each unit’s height range and orientation, then read the height difference at each seam. The square rising arrangement retains an 8 cm step.", "用圆环或方环连接出台阶、坡道和围合空间。调节每个单元的高度范围和朝向，查看接缝高差。方环升台组合保留一道 8 厘米台阶。"],
  ["Descent · rise · enclosure · step · ramp · three-part ramp · hollow · arch", "坡降 · 升台 · 合腔 · 台阶 · 续坡 · 三段坡 · 凹 · 拱"],
  ["Round from Lab 2-5 · square from Lab 2-7", "圆环来自实验 2-5 · 方环来自实验 2-7"],
  ["Crest band 0–19 · height slice 0–100% · split opening direction", "波峰条带 0–19 · 高度区间 0–100% · 捏分开口朝向"],
  ["Round 0.35 m · square 0.16 m", "圆环 0.35 米 · 方环 0.16 米"],
  ["Level within 3 cm · square rise includes an 8 cm step", "高差 3 厘米内视为齐平 · 方环升台有 8 厘米台阶"],
  ["Touching at peak reach or separated by the family’s gap", "按最大挑出相接，或留出该族环间缝"],
  ["1.70 m figure · round surface 1.39–1.73 m · cavity height 0.39 m", "人物 1.70 米 · 圆环走面 1.39–1.73 米 · 腔高 0.39 米"],
  ["Single-row assembly; no interaction between units", "单排装配；未模拟单元间相互作用"],
  ["Four-bar linkage", "四杆连杆"],
  ["Drag a joint to move the four-bar mechanism and trace its path.", "拖动节点，观察四杆机构的运动与轨迹。"],
  ["Arch ring solver", "拱环求解器"],
  ["The S4 scissor arch, driven by a crank-slider.", "由曲柄滑块驱动的 S4 剪式拱环。"],
  ["Tendon tentacle", "肌腱触手"],
  ["Bend seven vertebrae with three tendons spaced at 120°.", "三条相隔 120° 的肌腱控制七节触手弯曲。"],
  ["Five-ring shell", "五环外壳"],
  ["Five rings opening and closing together.", "五个环同步开合。"],
  ["Full assembly", "整机装配"],
  ["One shaft drives five rings; three tendons bend the arm.", "一根轴驱动五环，三条肌腱控制触手。"],
  ["Contractile skin units", "收缩张紧外皮单元"],
  ["Four bond patterns turn a contracting strip into four shapes.", "四种锁定键排布，让同一条带收缩成四种形态。"],
  ["Skin units, solid", "皮肤单元立体带"],
  ["The four fabric bands in 3D, with visible sections and bonds.", "在三维视图中查看四种织物带的剖面与键。"],
  ["Two structures, one band", "一条带、两个结构"],
  ["Two structures on one strip, with an adjustable gap.", "同一条带形成两个结构，中间间距可调。"],
  ["Series", "序列"],
  ["Compare a graded series with a platform splitting in two.", "对比形态渐变序列与平台捏分序列。"],
  ["Cylinder of units", "圆筒环"],
  ["Twenty bands form a level, undulating, changing, split or double platform.", "二十条带围成等高、起伏、渐变、捏分或双层平台。"],
  ["Layers within one unit", "单元内的多层台"],
  ["Adjust each shelf’s radius, outline, tilt and joined sectors.", "分别调节上下层的半径、轮廓、倾角和连接区域。"],
  ["A square ring", "方形环"],
  ["Vary each band’s reach to change a round platform into a square.", "改变各条带的挑出距离，让圆形平台逐步变方。"],
  ["Four by four", "四乘四阵列"],
  ["Sixteen rings in a room, with a 1.70 m figure for scale.", "十六个环放入房间，以 1.70 米人物标示比例。"],
  ["Between units", "单元关系"],
  ["Arrange 2, 3, 4 or 9 rings and compare their spacing, heights and timing.", "组合 2、3、4 或 9 个环，比较间距、高差与成形时序。"],
  ["A person walks through", "一个人走过"],
  ["Move one person and watch nearby units respond to their floor trace.", "移动一个人，观察附近单元如何响应地面痕迹。"],
  ["A few people", "几个人在场"],
  ["Place or drag people to see how their overlapping views affect the units.", "放置或拖动人物，观察视野重叠对单元的影响。"],
  ["Joined platforms", "平台组合"],
  ["Join round or square platforms into steps, ramps and enclosures.", "用圆环或方环连接出台阶、坡道和围合空间。"],
  ["drag a joint", "拖动节点"],
  ["drag the apex", "拖动拱顶"],
  ["drag to orbit", "拖动旋转"],
  ["views by button", "按钮切换视角"],
  ["drag ℓ", "拖动 ℓ"],
  ["drag the person", "拖动人物"],
  ["click to add", "点击添加人物"],
  ["SVG · 2D kernel", "矢量 · 二维内核"],
  ["WebGL · 3D kernel", "WebGL · 三维内核"],
  ["WebGL · fixed view", "WebGL · 固定视角"],
  ["SVG · research-code port", "矢量 · 研究代码移植"],
  ["WebGL · multi-view", "WebGL · 多视图"],
  ["WebGL · 16 live rings", "WebGL · 16 个实时环"],
  ["Canvas · plan", "Canvas · 平面"],
  ["Canvas · up to 8 people", "Canvas · 最多 8 人"],
  ["Moves the page — never the model.", "只翻页面，不动模型。"],
  ["Works straight away: orbit, pull a joint, move a person.", "直接可用：旋转视角、拉动节点、移动人物。"],
  ["Gives one bench the screen. The wheel then zooms; Esc restores.", "让一台实验占满屏幕，此时滚轮缩放模型；Esc 恢复。"],
  ["scroll", "滚动"],
  ["drag", "拖动"],
  ["expand ↗", "放大 ↗"],
  ["in progress", "进行中"],
  ["In progress", "进行中"],
  ["Case study ↗", "案例 ↗"],
  ["Notes", "说明"],
  ["Expand ↗", "放大 ↗"],
  ["Restore ↙", "恢复 ↙"],
  ["Index · collapse", "目录 · 收起"],
  ["Index · expand", "目录 · 展开"],
  ["About this study", "关于这项实验"],
  ["Fewer specs ↑", "收起规格 ↑"],
  ["03 · Project III — to come", "03 · 项目三 — 待建"],
  ["No benches yet. They will appear here, in build order, as the project takes shape.", "暂无实验。项目成形后，实验会按搭建顺序列在这里。"],
  ["Fixed view · switch it with the buttons", "固定视角 · 用按钮切换"],
  [" · wheel scrolls the page", " · 滚轮浏览页面"],
  ["Wheel zooms the model · drag to orbit · Esc restores", "滚轮缩放 · 拖动旋转 · Esc 恢复"],
  [" · Esc restores", " · Esc 恢复"],
  ["solve", "解什么"],
  ["view", "怎么看"],
  ["live", "运行中"],
  ["solving…", "求解中…"],
  ["Reincarnation Machine", "轮回机器"],
  ["Cross-species space", "跨物种空间"],
  ["two linkage kernels", "两套连杆内核"],
  ["shape-changing units and the behaviour that moves them", "会变形的单元，以及驱动它的行为"],
  ["Project III", "项目三"],
  ["Benches to come", "实验待建"]
];

const zhCopy = new Map(LAB_PAGE_COPY);
export function labPageText(lang: SiteLang, text: string): string {
  return lang === 'zh' ? zhCopy.get(text) ?? text : text;
}
