import type { SiteLang } from './lang';

/** Labels only: numerical parameters and solver keys are never translated. */
export const LAB_UI_COPY: readonly (readonly [string, string])[] = [
  ["一只猫在场", "A cat in the room"],
  ["拖动猫", "drag the cat"],
  ["画布 · 猫的行为", "Canvas · cat behaviour"],
  ["三类行为与自由运动 · 画布", "3 sequences + free movement · canvas"],
  ["实验室", "The lab"],
  ["实验目录", "Lab index"],
  ["目录", "Index"],
  ["收起目录", "Collapse index"],
  ["展开目录", "Expand index"],
  ["恢复默认宽度", "Reset widths"],
  ["恢复目录与说明的默认宽度", "Restore default index and details widths"],
  ["目录宽度", "Index width"],
  ["拖动或方向键调节", "Drag or use arrow keys"],
  ["像素", "pixels"],
  ["说明", "Details"],
  ["放大", "Expand"],
  ["恢复", "Restore"],
  ["实验说明", "About this study"],
  ["规格", "Specifications"],
  ["缩窄说明", "Narrow details"],
  ["加宽说明", "Widen details"],
  ["缩小模型", "Zoom out"],
  ["放大模型", "Zoom in"],
  ["归位", "Reset view"],
  ["滚轮浏览页面", "Scroll to browse"],
  ["放大后可触摸拖动", "Expand to drag on touchscreens"],
  ["滚轮缩放 · 拖动查看", "Scroll to zoom · drag to orbit"],
  ["直接操作实验", "Interact with the study"],
  ["全部实时运行", "All live"],
  ["二维内核", "2D kernel"],
  ["三维内核", "3D kernel"],
  ["可交互", "Interactive"],
  ["项目一 — 轮回机器", "Project I — Reincarnation machine"],
  ["项目二 — 跨物种空间", "Project II — Cross-species space"],
  ["项目一", "Project I"],
  ["项目二", "Project II"],
  ["轮回机器", "Reincarnation machine"],
  ["跨物种空间", "Cross-species space"],
  ["实验 1-1 – 1-6 · 两种连杆内核与一个行为引擎", "Lab 1-1 – 1-6 · two linkage kernels and a behaviour engine"],
  ["实验 2-1 – 2-14 · 会变形的单元，以及驱动它的行为", "Lab 2-1 – 2-14 · shape-changing units and the behaviour that moves them"],
  ["一条带", "One band"],
  ["一排", "A row"],
  ["一圈", "A ring"],
  ["一间房", "A room"],
  ["人", "People"],
  ["组合", "Compositions"],
  ["同台", "Together"],
  ["人猫同台", "People and cats together"],
  ["画布 · 两个物种", "Canvas · two species"],
  ["拖动人或猫", "drag a body"],
  ["3 档空间 · 4 类事件 · 画布", "3 spaces · 4 events · canvas"],
  ["实验 2-14 / 项目二", "Lab 2-14 / Project II"],
  ["实验 2-1 – 2-3 · 单元的结构", "Lab 2-1 – 2-3 · what a unit is"],
  ["实验 2-4 · 沿一排条带渐变", "Lab 2-4 · transitions along a line"],
  ["实验 2-5 – 2-7 · 将一排条带围成环", "Lab 2-5 – 2-7 · the row closed into a loop"],
  ["实验 2-8 · 真实比例的场地", "Lab 2-8 · the field at real scale"],
  ["实验 2-9 · 二、三、四、九个单元之间的关系", "Lab 2-9 · what two, three, four, nine units can be to each other"],
  ["实验 2-10 – 2-12 · 行为与单元响应", "Lab 2-10 – 2-12 · behaviour reaching the units"],
  ["实验 2-13 · 平台的高低连接", "Lab 2-13 · platforms joined high to low"],
  ["实验 2-14 · 人与猫同一间房，循环闭合", "Lab 2-14 · people and cats in one room, with the loop closed"],
  ["连杆、织物结构与空间行为的交互实验。拖动模型、调节控件，比较它们的运动和成形过程。", "Interactive studies of linkages, fabric structures and spatial behaviour. Drag the models and adjust their controls to compare how they move and form."],
  ["作品 →", "Work →"],
  ["日志 →", "Log →"],
  ["内核", "Kernel"],
  ["测试", "Tests"],
  ["绘制", "Render"],
  ["驱动", "Drive"],
  ["实例", "Instance"],
  ["止程", "Stops"],
  ["网格", "Mesh"],
  ["相机", "Camera"],
  ["环族", "Family"],
  ["编排", "Choreo"],
  ["峰值误差", "Peaks"],
  ["实体", "Bodies"],
  ["行程", "Stroke"],
  ["触手", "Arm"],
  ["说明与限制", "Caveats"],
  ["来源", "Source"],
  ["键", "Bonds"],
  ["条带", "Band"],
  ["形态组合", "Pairs"],
  ["间隙", "Gap"],
  ["独立性", "Independence"],
  ["序列", "Series"],
  ["渐变", "Gradient"],
  ["捏分", "Split"],
  ["形态偏差", "Shape fit"],
  ["排布", "Layout"],
  ["环", "Ring"],
  ["起伏", "Undulation"],
  ["双层", "Double"],
  ["半径", "Radius"],
  ["蒙皮", "Skin"],
  ["限制", "Limit"],
  ["视图", "Views"],
  ["基准", "Baseline"],
  ["倾角", "Tilt"],
  ["轮廓", "Outline"],
  ["连接", "Joins"],
  ["成形", "Forming"],
  ["条带数", "Bands"],
  ["等高", "Flat"],
  ["挑出距离", "Reach"],
  ["捏分轮廓", "Split outline"],
  ["场地", "Field"],
  ["比例", "Scale"],
  ["高度", "Height"],
  ["间距", "Spacing"],
  ["形态", "Forms"],
  ["单元", "Unit"],
  ["组合数量", "Clusters"],
  ["关系", "Relations"],
  ["交叠", "Interleave"],
  ["时序", "Timing"],
  ["接缝", "Seams"],
  ["格数", "Grid"],
  ["痕迹", "Trace"],
  ["读法", "Reading"],
  ["演示参数", "Demo"],
  ["视野", "View"],
  ["让位", "Clearance"],
  ["原型", "Prototype"],
  ["自走", "Wander"],
  ["响应", "Response"],
  ["重叠", "Overlap"],
  ["图形", "Figures"],
  ["单元族", "Units"],
  ["控件", "Controls"],
  ["范围", "Range"],
  ["运转", "Run"],
  ["跳过成形", "Skip forming"],
  ["键线", "Bond lines"],
  ["透视", "Perspective"],
  ["重播", "Replay"],
  ["速度", "Speed"],
  ["视角", "Camera view"],
  ["肌腱", "Tendons"],
  ["联动", "Link"],
  ["放松", "Relax"],
  ["视角归位", "Reset camera"],
  ["无", "None"],
  ["排列", "Arrangement"],
  ["轴测", "Axon"],
  ["正", "Front"],
  ["侧", "Side"],
  ["顶", "Top"],
  ["编制", "Pattern"],
  ["距离", "Distance"],
  ["袋", "Pocket"],
  ["蘑菇挑台", "Bulb flange"],
  ["直挑台", "Straight ledge"],
  ["阶梯挑台", "Stepped box"],
  ["目录渐变", "Graded"],
  ["并拢", "Packed"],
  ["分列", "Spread"],
  ["一圈起伏", "Undulating"],
  ["整环同形", "Uniform"],
  ["一圈渐变", "Changing"],
  ["双层台", "Double shelf"],
  ["整环平", "Level"],
  ["单环", "Single ring"],
  ["整片同形", "Uniform field"],
  ["每行一种", "By row"],
  ["圆", "Circle"],
  ["微方", "Soft square"],
  ["半方", "Half square"],
  ["近方", "Near square"],
  ["方", "Square"],
  ["二 · 一对", "2 · Pair"],
  ["三 · 三角", "3 · Triad"],
  ["四 · 方阵", "4 · Grid"],
  ["九 · 九宫", "9 · Grid"],
  ["分离 · 齐平", "Apart · level"],
  ["相切 · 齐平", "Touching · level"],
  ["分离 · 错层", "Apart · stepped"],
  ["相切 · 错层", "Touching · stepped"],
  ["交叠 · 错层", "Interleaved"],
  ["同步", "Together"],
  ["错相", "Staggered"],
  ["① 坡降", "① Descent"],
  ["② 升台", "② Rise"],
  ["③ 合腔", "③ Enclosure"],
  ["台阶", "Step"],
  ["续坡", "Ramp"],
  ["三段坡", "Three-part ramp"],
  ["凹", "Hollow"],
  ["拱", "Arch"],
  ["圆环", "Round"],
  ["方环", "Square ring"],
  ["相切", "Touching"],
  ["分离", "Apart"],
  ["查看", "Inspect"],
  ["目标形态", "Target geometry"],
  ["条带成形", "Forming bands"],
  ["示例", "Presets"],
  ["编辑", "Edit"],
  ["上层", "Upper"],
  ["下层", "Lower"],
  ["完整度", "Coverage"],
  ["环形轮廓", "Ring shape"],
  ["整环", "Full ring"],
  ["半环", "Half ring"],
  ["局部厚台", "Thick sector"],
  ["整圆", "Full circle"],
  ["半圆", "Half circle"],
  ["四分之一", "Quarter"],
  ["三分之二", "Two thirds"],
  ["分离双扇", "Two sectors"],
  ["单区", "One sector"],
  ["对向双区", "Opposite sectors"],
  ["双层基准", "Double baseline"],
  ["对向倾斜", "Opposed tilts"],
  ["错位缺口", "Offset gaps"],
  ["对称厚台", "Opposite thick sectors"],
  ["图示组合", "Sketch assembly"],
  ["下坡方向", "Downhill direction"],
  ["平台半径", "Shelf radius"],
  ["连接深度", "Join depth"],
  ["轮廓方位", "Outline rotation"],
  ["单区范围", "Sector angle"],
  ["起点方位", "Start angle"],
  ["起点", "Start"],
  ["目标剖面方向", "Section direction"],
  ["整圈条带", "Whole ring"],
  ["台部特写", "Shelf detail"],
  ["截面对照", "Sections"],
  ["倾斜装配", "Tilt preview"],
  ["对向连接", "Opposite joins"],
  ["收缩中", "Contracting"],
  ["张紧 · 排泡", "Tensioning"],
  ["锁定 · 即将重播", "Locked · replaying"],
  ["锁定 · 终态", "Locked · final state"],
  ["终态加载中", "Loading final state"],
  ["终态加载失败 · 点重播重试", "Loading failed · replay to retry"],
  ["拖拽旋转", "Drag to orbit"],
  ["拖拽旋转 · 右键平移", "Drag to orbit · right-drag to pan"],
  ["原始求解节点 · 拖拽旋转 · 滚轮缩放", "Solved nodes · drag to orbit · scroll to zoom"],
  ["目标形态 · 几何原型", "Target geometry · spatial prototype"],
  ["上层绿 · 下层紫 · 连接金", "Upper green · lower purple · joins gold"],
  ["形态参数与图纸 · 点击展开 / 收起", "Parameters and drawings · click to expand or collapse"],
  ["所选扇区没有上下重叠，未形成连接。", "The selected sectors do not overlap; no join is formed."],
  ["上方图纸为目标轮廓与目标剖面；两种查看方式共用这组参数。", "The drawings show target outlines and sections. Both views share these parameters."],
  ["条带独立成形，带间留空。倾斜仅作装配预览，未模拟环向受力。截面从左至右：双层、厚台、仅上层、仅下层。", "Bands form independently, with gaps between them. Tilt is an assembly preview; circumferential forces are not simulated. Sections: double, thick, upper only, lower only."],
  ["直接载入已算好的成形状态；取消勾选可从头观看成形过程", "Load the computed final state; uncheck to watch it form from the start."],
  ["播放速度（协议步/秒的倍率，不是物理量）", "Playback rate, not a physical parameter"],
  ["环间织物膜的不透明度（0 = 只剩带子，1 = 封闭的筒）", "Membrane opacity: 0 shows bands only; 1 closes the cylinder"],
  ["圆筒半径（世界单位；越大缝越宽）", "Ring radius in model units; larger radii widen the gaps"],
  ["每行一种编制下由行号决定", "The row determines the form in this pattern."],
  ["全场一个时钟", "All units share one clock."],
  ["方环只有它自己的箱", "The square family uses its own box section."],
  ["这张图形没有起伏单元", "This figure has no undulating units."],
  ["边贴边（按挑出峰值）", "Edges touch at maximum reach."],
  ["再加各族自己的环间缝", "Add the gap defined for this ring family."],
  ["圆筒环（Lab 2-5）· 起伏量程 0.35 m · 半径可调", "Round ring (Lab 2-5) · height range 0.35 m · adjustable radius"],
  ["方形环（Lab 2-7）· 起伏量程 0.16 m · 半径按 30 标定", "Square ring (Lab 2-7) · height range 0.16 m · radius fixed at 30"],
  ["紧凑（草图间距；合法下限——无一条约束跨两个结构）", "Compact: minimum spacing; no bond crosses both structures."],
  ["逐位解耦下限：拿掉一个结构，另一个逐位不变", "Independent: removing one structure leaves the other unchanged."],
  ["拉开读（两结构远隔）", "Spread: separate the two structures for inspection."],
  ["渐变编制下由 11 级键谱决定", "The graded pattern uses 11 bond maps."],
  ["捏分编制下由 10 级键谱决定", "The split pattern uses 10 bond maps."],
  ["双层台沿整圈复用捏分的全开双平台", "The double shelf repeats the fully open split section."],
  ["3D 视图不可用；下方俯视和剖面仍可操作。", "3D view unavailable; plan and section controls still work."],
  ["WebGL 不可用", "WebGL unavailable"],
  ["WebGL 初始化失败", "WebGL initialization failed"],
  ["3D mesh 载入失败", "3D mesh loading failed"],
  ["该层相对水平面的倾斜角度，仅用于装配预览。", "Tilt from the horizontal, for assembly preview only."],
  ["改变该层向哪一侧倾斜。", "Choose the direction in which this layer slopes down."],
  ["旋转该层轮廓，调整缺口朝向。", "Rotate the outline to change the gap direction."],
  ["每个连接扇区的角度；只连接上下层重叠处。", "Angle of each joined sector; only overlapping layers join."],
  ["旋转连接扇区；对向双区一起转动。", "Rotate joined sectors; opposite sectors turn together."],
  ["旋转剖切平面，查看不同方向的上下层关系。", "Rotate the section plane to inspect the two layers."],
  ["实验", "Lab"],
  ["相机控制", "Camera controls"],
  ["说明宽度", "Details width"],
  ["说明与规格", "Details and specifications"],
  ["· 放大后可触摸拖动", "· Expand to drag on touchscreens"],
  ["操作说明", "How to use"],
  ["行为与成形", "Behaviour and forming"],
  ["步", "step"],
  ["· 键", "· bonds"],
  ["顶高", "apex"],
  ["mm · 误差", "mm · err"],
  ["· 误差", "· err"],
  ["自动驱动", "driven"],
  ["拖动中", "dragging"],
  ["回接中", "blending"],
  ["Grashof 曲柄摇杆台架；拖任意自由节点驱动", "Grashof crank-rocker; drag a free joint to drive it"],
  ["Grashof 曲柄摇杆", "Grashof crank-rocker"],
  ["2D PBD · Gauss–Seidel · L 66·178·127 · 板 132·100", "2D PBD · Gauss–Seidel · L 66·178·127 · plate 132·100"],
  ["拖任意自由节点 · 松手继承角速度", "Drag a free joint · release to continue at its angular velocity"],
  ["· 俯视", "· Plan"],
  ["剖面 ·", "Section ·"],
  ["剖面", "Section"],
  ["俯视轮廓", "Plan outline"],
  ["单元内的多层台：可旋转的目标几何，绿色上层、紫色下层、金色连接区域", "Layers within one unit: orbit the target geometry; upper layer green, lower purple, joins gold"],
  ["局部厚台连接", "Thick sector joins"],
  ["· 两区相隔 180°，一起转动", "· Opposite sectors rotate together, 180° apart"],
  ["成形验证", "Forming study"],
  ["单元内的多层台", "Layers within one unit"],
  ["静止", "idle"],
  ["自转", "spin"],
  ["拖动", "drag"],
  ["回接", "release"],
  ["误差", "err"],
  ["三维预览暂不可用", "3D preview unavailable"]
];
const toEnglish = new Map(LAB_UI_COPY);
const toChinese = new Map(LAB_UI_COPY.map(([zh, en]) => [en.toLowerCase(), zh]));
export function labUiText(lang: SiteLang, text: string): string {
  const translated = (lang === 'zh' ? toChinese : toEnglish).get(lang === 'zh' ? text.toLowerCase() : text);
  if (translated) return translated;
  // Bench identifiers are display labels; solver keys and values never pass here.
  if (lang === 'zh' && /^Lab \d/i.test(text)) return text.replace(/^Lab /i, '实验 ').replace(/Project II\b/g, '项目二').replace(/Project I\b/g, '项目一').replace(/Fig\./g, '图');
  return text;
}
